parameters:
#    blog_app.example.class: Blog\AppBundle\Example

services:
#    blog_app.example:
#        class: %blog_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
